### ISSUE TITLE
Price one hour off

### ISSUE THREAD

**Issue by pelti51** [balmli/com.nordpoolspot#1]
The price value is one hour off. For example currently 10.7.2019 8:27 the app says that the price is 42,62€/MWh in Finland area. When you look at the nordpool data https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/ALL1/Hourly/?view=table
the price should be 42,31€/MWh the shown price in the app should be the 07:00-08:00 price. Maybe a daylight savings time error?

Otherwise the app seems to be working and I'm really enjoying it.  Keep up the good work!

**Comment by balmli** [comment]
Thanks for reporting this.  

Yes, there must be a timezone bug.

**Comment by pelti51** [comment]
Checked the timezone of the Nord Pool data. The data is given in CET/CEST so there is 1 hour time difference between Finland local time and CET/CEST.

Conclusion, your app works correctly and gives the correct hour prices. Case closed.
