### ISSUE TITLE
Feil spotpris

### ISSUE THREAD

**Issue by janeven** [balmli/com.nordpoolspot#3]
Variabel Price var i dag 12.2.2021 kl 0700: 1
Kl 0800: 2 osv
Først kl 1100 korrekt verdi igjen: 801.05

Sone Oslo i NOK:
06 - 07 645,81
07 - 08	1 748,50
08 - 09 2 566,59
09 - 10 2 035,16
10 - 11 1 211,22
11 - 12 801,05

Hentet fra
https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/NO/Hourly/?view=table

**Comment by janeven** [comment]
![Screenshot_20210212-145012.png](https://user-images.githubusercontent.com/218941/107777611-5b7bab80-6d43-11eb-848c-d37f6ea5d203.png)

**Comment by balmli** [comment]
Beklager, men vedlikeholder ikke dette repoet..
