### ISSUE TITLE
Whitespace in high prices

### ISSUE THREAD

**Issue by Precisionsflyg** [balmli/com.nordpoolspot#4]
When prices are above 1000, Nordpool adds a whitespace after the thousands:

{"Index":4,"Scale":2,"SecondaryValue":null,"IsDominatingDirection":false,"IsValid":true,"IsAdditionalData":false,"Behavior":0,"Name":"SE4","Value":"1 117,05","GroupHeader":"","DisplayNegativeValueInBlue":false,"CombinedName":"SE4","DateTimeForData":"0001-01-01T00:00:00","DisplayName":"1 117,05_False","DisplayNameOrDominatingDirection":"1 117,05","IsOfficial":false,"UseDashDisplayStyle":false},

_From `https://www.nordpoolgroup.com/api/marketdata/page/10?endDate=15-02-2021&currency=SEK`_

This breaks parseFloat it would seem...

**Comment by Precisionsflyg** [comment]
Will try this when I get home, in nordpool.js line 31:
```
var value = column.Value.replace(' ', ''));
value = parseFloat(value.replace(/,/, '.'));
```

**Comment by balmli** [comment]
Ok, thank you for reporting!

I will fix this.

**Comment by balmli** [comment]
Seems I fixed in on January 27th

`var value = Math.round(100000 * (parseFloat(column.Value.replace(/,/, '.').replace(' ', '')) / 1000.0)) / 100000;
`

**Comment by Precisionsflyg** [comment]
Ok, has the file on Github been updated? Last commit January 8th, 2019.

**Comment by balmli** [comment]
Sorry, I was looking at this repo: https://github.com/balmli/no.almli.heatingcontroller


com.nordpoolspot is not something that I maintain

**Comment by Precisionsflyg** [comment]
Ok. :-D
I'll try updating it when I get home. It's a great app BTW!

**Comment by balmli** [comment]
You also have the "Heating Controller" app in app store, and also "Spot prices".
